# headers.py
# # This file contains entity headers for the Seer PAS SDK.


PLATE_COLUMNS = [
    "id",
    "plate_name",
    "plate_id",
    "description",
    "notes",
    "created_by",
    "created_timestamp",
    "last_modified_by",
    "last_modified_timestamp",
    "space",
]

PROJECT_COLUMNS = [
    "id",
    "project_name",
    "description",
    "notes",
    "created_by",
    "created_timestamp",
    "last_modified_by",
    "last_modified_timestamp",
    "plates",
    "sampleTypes",
    "space",
]

SAMPLE_COLUMNS = [
    "id",
    "plate_id",
    "sample_name",
    "sample_id",
    "sample_type",
    "species",
    "description",
    "notes",
    "created_by",
    "created_timestamp",
    "last_modified_by",
    "last_modified_timestamp",
    "sample_receipt_date",
    "sample_collection_date",
    "condition",
    "plate_name",
    "biological_replicate",
    "technical_replicate",
    "well_location",
    "control",
    "space",
]

ANALYSIS_COLUMNS = [
    "id",
    "analysis_name",
    "description",
    "notes",
    "analysis_protocol_id",
    "analyzed_by",
    "start_time",
    "end_time",
    "last_modified_by",
    "last_modified_timestamp",
    "status",
    "result_folder",
    "job_id",
    "space",
    "project_id",
    "number_msdatafile",
    "protein_group_count",
    "single_protein_group_count",
    "possible_protein_set_size",
    "peptides_count",
    "contains_control",
    "job_log_stream_name",
    "contains_sample",
    "is_folder",
    "folder_id",
    "number_sample",
    "total_file_size_mb",
    "msdatafile_extensions",
    "fasta",
]

ANALYSIS_PROTOCOL_COLUMNS = [
    "id",
    "analysis_protocol_name",
    "analysis_type",
    "version_number",
    "description",
    "notes",
    "created_by",
    "created_timestamp",
    "parameter_file_path",
    "species",
    "alg_version",
    "analysis_engine",
    "offering_name",
    "based_on",
    "retired",
    "use_normalization",
    "pipeline_w_version",
    "archived",
    "last_modified_by",
    "last_modified_timestamp",
    "go_version",
    "space",
    "fasta",
]

MSRUN_COLUMNS = [
    "id",
    "raw_file_path",
    "sample_id",
    "sample_id_tracking",
    "well_location",
    "nanoparticle",
    "nanoparticle_id",
    "control",
    "control_id",
    "instrument_name",
    "date_sample_prep",
    "sample_volume",
    "peptide_concentration",
    "peptide_mass_sample",
    "dilution_factor",
    "kit_id",
    "created_by",
    "created_timestamp",
    "last_modified_by",
    "last_modified_timestamp",
    "injection_timestamp",
    "ms_instrument_sn",
    "recon_volume",
    "gradient",
    "assay_product",
    "method_set_id",
    "assay_method_id",
    "sample_tube_id",
    "space",
]
