name: Publish

on:
  workflow_dispatch:  # TODO: remove after testing
  release:
    types: [created]

jobs:
  deploy-pkg:
    name: Upload release to internal CodeArtifact
    runs-on: [self-hosted, X64]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip config unset global.index-url || true  # Ensure we don't have old CodeArtifact creds in pip config
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build
          aws codeartifact login --tool twine --repository seer_ds --domain seer --domain-owner 718843040700 --region us-west-2
      - name: Build package for pas-python-sdk
        run: |
          python -m build --sdist --wheel .
      - name: Publish package to CodeArtifact
        run: |
          twine upload --repository codeartifact dist/*

  build-docs:
    runs-on: ubuntu-latest
    needs: deploy-pkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # minimum for new-enough quartodoc
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Set up QuartoDoc + Jupyter

        run: pip install 'quartodoc>=0.7.6' jupyter

      - name: Install seer-pas-sdk
        run: pip install .  # Install SDK libs so quartodoc can find them
      - name: Render documentation
        run: |
          cd docs/
          quartodoc build --verbose
          quarto render
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_site/

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
