name: Publish

on:
  workflow_dispatch:  # TODO: remove after testing
  release:
    types: [created]

jobs:
  deploy-pkg:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build
      - name: Build package for seer-pas-sdk
        run: python -m build --sdist --wheel .
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  build-docs:
    runs-on: ubuntu-latest
    needs: deploy-pkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # minimum for new-enough quartodoc
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Set up QuartoDoc + Jupyter
        run: pip install 'quartodoc>=0.7.0' jupyter
      - name: Install seer-pas-sdk
        run: pip install .  # Install SDK libs so quartodoc can find them
      - name: Render documentation
        run: |
          cd docs/
          quartodoc build --verbose
          quarto render
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_site/

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
